---
- name: ensure required Vim and Vim-related packages exist
  package:
    name: "{{ vim_installed_packages }}"
    state: present

- name: remove unneeded Vim-related packages
  package:
    name: "{{ vim_removed_packages }}"
    state: absent
