---
- name: remove {{ plugin_data.type }} plugins.
  file:
    path: "{{ vim_plugins_parent_directory }}/{{ plugin_data.directory }}/{{ plugin }}"
    state: absent
  loop: "{{ plugin_data.list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest
  when: vim_version.stdout is version('8.0', '>=')

- name: remove pathogen plugins.
  file:
    path: "{{ vim_plugins_pathogen_directory }}/{{ plugin }}"
    state: absent
  loop: "{{ plugin_data.list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest
  when: vim_version.stdout is version('8.0', '<=')
